# Generation configuration (shared parameters)
generation: &generation
  max_len: &max_len 512
  group_size: &group_size 8
  temperature: &temperature 0.6
  top_k: &top_k -1
  top_p: &top_p 1.0
  min_p: &min_p 0.0
  batch_size: &generation_batch_size 4

# Model configuration
model:
  name: "joey00072/Llama-3.2-1B-Instruct-cold-start-ft2"
  revision: null
  dtype: "bfloat16"
  max_model_len: *max_len

# LoRA configuration
lora:
  enabled: true
  r: 8
  alpha: 16
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "down_proj", "up_proj"]

# GRPO training configuration
grpo:
  group_size: *group_size
  micro_group_size: 1
  batch_size: 1
  lr: 0.000005
  weight_decay: 0.1
  beta: 0.0
  epsilon: 0.2
  log_wandb: true
  wandb_project: "fuchsia-jee-deephermes"
  num_policy_updates: 8
  lora_path: "/mnt/nvme0n1/joey/experiments/lora_weights3"

# Server configuration
server:
  host: "0.0.0.0"
  port: 8000
  gpu_memory_utilization: 0.50
  tensor_parallel_size: 1
  enable_prefix_caching: false
  buffer_size: 4
  generation_batch_size: *generation_batch_size
  quantization: null
  vllm:
    max_tokens: *max_len
    n: *group_size
    temperature: *temperature
    top_p: *top_p
    top_k: *top_k
    min_p: *min_p

# Dataset configuration
dataset:
  name: "AthenaAgent42/jee_papers"
  split: "train"
  max_samples: null
  field: "text"

# Training configuration
training:
  max_epochs: 1
  max_iterations: 1000
  save_steps: 100
  eval_steps: 50
  output_dir: "jee_output" 


# 8k 246.2914233800002
# 16k 537.8559579419998
